variables:
  PYTHON_VERSION: "3.8"

jobs:
- job: Windows
  pool:
    vmImage: $(AZP_BUILD_WORKER_IMAGE)
  timeoutInMinutes: 180
  steps:
  - task: UsePythonVersion@0
    condition: ne(variables.CONAN_VISUAL_VERSIONS, 14)
    inputs:
      versionSpec: $(PYTHON_VERSION)
  - task: PowerShell@2
    condition: eq(variables.CONAN_VISUAL_VERSIONS, 14)
    inputs:
      targetType: inline
      script: |
        Invoke-WebRequest https://www.python.org/ftp/python/3.8.0/python-3.8.0-amd64-webinstall.exe -OutFile C:\py3-setup.exe
        C:\py3-setup.exe /quiet PrependPath=1 InstallAllUsers=1 Include_launcher=1 InstallLauncherAllUsers=1 Include_test=0 Include_doc=0 Include_dev=0 Include_debug=0 Include_tcltk=0 TargetDir=C:\Python3 | Out-Null
        Write-Host "##vso[task.prependpath]C:\Python3"
        Write-Host "##vso[task.prependpath]C:\Python3\Scripts"
        Invoke-WebRequest -OutFile get-pip.py https://bootstrap.pypa.io/get-pip.py
        C:\Python3\python.exe get-pip.py
        Remove-Item C:\py3-setup.exe
        Remove-Item get-pip.py
        Remove-Item $env:TEMP -Recurse -Force -ErrorAction SilentlyContinue
        $rmvfolders = @( “C:\Windows\Temp\*”, “C:\Windows\Prefetch\*”, “C:\Documents and Settings\*\Local Settings\temp\*”, “C:\Users\*\Appdata\Local\Temp\*”, “C:\NPM\*“, “C:\java\*“, “C:\cordova\*“, “C:\Program Files\nodejs\*“, “C:\Python27\*“ )
        Remove-Item $rmvfolders -Recurse -Force
    displayName: UsePythonVersion for VS 2015
  - script: |
      echo %PATH%
      python --version
      pip --version
      pip install bincrafters_package_tools
      conan user
    displayName: Install Conan
  - script: |
      python build.py
    env:
      CONAN_LOGIN_USERNAME: $(CONAN_LOGIN_USERNAME)
      CONAN_PASSWORD: $(CONAN_PASSWORD)
    displayName: Run

  strategy:
    matrix:
      VS 2015 Release:
        AZP_BUILD_WORKER_IMAGE: vs2015-win2012r2
        CONAN_VISUAL_VERSIONS: 14
        CONAN_BUILD_TYPES: Release
      VS 2015 Debug:
        AZP_BUILD_WORKER_IMAGE: vs2015-win2012r2
        CONAN_VISUAL_VERSIONS: 14
        CONAN_BUILD_TYPES: Debug
      VS 2017 Release:
        AZP_BUILD_WORKER_IMAGE: vs2017-win2016
        CONAN_VISUAL_VERSIONS: 15
        CONAN_BUILD_TYPES: Release
      VS 2017 Debug:
        AZP_BUILD_WORKER_IMAGE: vs2017-win2016
        CONAN_VISUAL_VERSIONS: 15
        CONAN_BUILD_TYPES: Debug
      VS 2019 Release:
        AZP_BUILD_WORKER_IMAGE: windows-2019
        CONAN_VISUAL_VERSIONS: 16
        CONAN_BUILD_TYPES: Release
      VS 2019 Debug:
        AZP_BUILD_WORKER_IMAGE: windows-2019
        CONAN_VISUAL_VERSIONS: 16
        CONAN_BUILD_TYPES: Debug


- job: macOS
  pool:
    vmImage: $(AZP_BUILD_WORKER_IMAGE)
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: $(PYTHON_VERSION)
  - script: |
      pip install --upgrade pip
      python --version
      pip --version
      chmod +x .ci/install.sh
      ./.ci/install.sh
      chmod +x .ci/run.sh
    displayName: Install Conan
  - script: |
      ./.ci/run.sh
    env:
      CONAN_LOGIN_USERNAME: $(CONAN_LOGIN_USERNAME)
      CONAN_PASSWORD: $(CONAN_PASSWORD)
    displayName: Run
  
  strategy:
    matrix:
      Apple-Clang 10 Release:
        AZP_BUILD_WORKER_IMAGE: macOS-10.13
        CONAN_APPLE_CLANG_VERSIONS: 10.0
        CONAN_BUILD_TYPES: Release
      Apple-Clang 10 Debug:
        AZP_BUILD_WORKER_IMAGE: macOS-10.13
        CONAN_APPLE_CLANG_VERSIONS: 10.0
        CONAN_BUILD_TYPES: Debug
